### ISSUE TITLE
save coordinates of each sample in PCA plot

### ISSUE THREAD

**Issue by pontikos** [UCLGeneticsInstitute/DNASeq_pipeline#1]
In order to be able to determine where each individual lies in the PCA plot we need to save the plot data before plotting.
That way we can also use plotly for interactive visualisation.

**Comment by CianMurphy** [comment]
plot data will now be saved in paste0(oDir,'pca.plot.RData'). Initial plotly graph: https://plot.ly/~CianMurphy/0/v4-vs-v3/#plot

**Comment by pontikos** [comment]
Very nice!  I think it's possible to save the plotly locally so we can then render it via the web browser.

**Comment by CianMurphy** [comment]
oh right. Ill see if i can do that too. Looks so much better than a low resolution pga. cant wait to see it being used
